-- MySQL Script generated by MySQL Workbench
-- Sun Oct 21 15:08:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ccm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ccm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ccm` DEFAULT CHARACTER SET utf8 ;
USE `ccm` ;

-- -----------------------------------------------------
-- Table `ccm`.`bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccm`.`bank` ;

CREATE TABLE IF NOT EXISTS `ccm`.`bank` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `wx_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `wx_id_UNIQUE` (`wx_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ccm`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccm`.`user` ;

CREATE TABLE IF NOT EXISTS `ccm`.`user` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `is_deleted` TINYINT(4) NULL DEFAULT 0,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `creator` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ccm`.`credit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccm`.`credit_card` ;

CREATE TABLE IF NOT EXISTS `ccm`.`credit_card` (
  `id` VARCHAR(50) NOT NULL,
  `bank_id` VARCHAR(100) NOT NULL,
  `number` VARCHAR(50) NOT NULL,
  `statement_date` TINYINT(4) NULL DEFAULT NULL,
  `payment_date` TINYINT(4) NULL DEFAULT NULL,
  `creator` VARCHAR(50) NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `is_deleted` TINYINT(4) NULL DEFAULT 0,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `bank_id_idx` (`bank_id` ASC),
  INDEX `creator_idx` (`creator` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  CONSTRAINT `creator`
    FOREIGN KEY (`creator`)
    REFERENCES `ccm`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bank_id`
    FOREIGN KEY (`bank_id`)
    REFERENCES `ccm`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ccm`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccm`.`transaction` ;

CREATE TABLE IF NOT EXISTS `ccm`.`transaction` (
  `id` VARCHAR(50) NOT NULL,
  `credit_card_id` VARCHAR(50) NOT NULL,
  `amount` INT(11) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `merchant` VARCHAR(200) NULL DEFAULT NULL,
  `creator` VARCHAR(50) NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT NULL,
  `is_deleted` TINYINT(4) NULL DEFAULT 0,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `credit_card_id_idx` (`credit_card_id` ASC),
  INDEX `creator_idx` (`creator` ASC),
  CONSTRAINT `credit_card_id`
    FOREIGN KEY (`credit_card_id`)
    REFERENCES `ccm`.`credit_card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transcation_creator`
    FOREIGN KEY (`creator`)
    REFERENCES `ccm`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
